const db = require('../config/db');

async function getCertificateDetails(req, res) {
  try {
    const { student_pin } = req.params;
    const cleanPin = student_pin.trim();

    // Security check: if student role, they can only view their own certificate
    if (req.user && req.user.role === 'student' && req.user.pin !== cleanPin) {
      return res.status(403).json({ success: false, error: 'Access denied: You can only view your own certificate.' });
    }

    // Fetch current active certificate version
    const versionRes = await db.query(
      'SELECT * FROM certificate_versions WHERE student_pin = $1 AND is_current = 1',
      [cleanPin]
    );

    if (versionRes.rows.length === 0) {
      return res.status(404).json({
        success: false,
        error: 'No generated certificate found for this student. Clearance may be pending or certificate has not been generated by the Clerk.'
      });
    }

    const cert = versionRes.rows[0];

    return res.json({
      success: true,
      certificate: cert
    });
  } catch (err) {
    console.error('getCertificateDetails error:', err);
    return res.status(500).json({ success: false, error: 'Failed to fetch certificate details.' });
  }
}

async function getCertificateByVersion(req, res) {
  try {
    const { student_pin, version } = req.params;
    const cleanPin = student_pin.trim();
    const versionNum = parseInt(version, 10);

    // Only Clerk can view specific/superseded versions
    if (!req.user || req.user.role !== 'clerk') {
      return res.status(403).json({
        success: false,
        error: 'Superseded certificate versions are internal records accessible only by the Clerk.'
      });
    }

    const versionRes = await db.query(
      'SELECT * FROM certificate_versions WHERE student_pin = $1 AND version_number = $2',
      [cleanPin, versionNum]
    );

    if (versionRes.rows.length === 0) {
      return res.status(404).json({ success: false, error: `Certificate version v${versionNum} not found.` });
    }

    return res.json({
      success: true,
      certificate: versionRes.rows[0]
    });
  } catch (err) {
    console.error('getCertificateByVersion error:', err);
    return res.status(500).json({ success: false, error: 'Failed to fetch certificate version.' });
  }
}

async function getNoDuesFormData(req, res) {
  try {
    const { student_pin } = req.params;
    const cleanPin = student_pin.trim();

    // Fetch student master record
    const masterRes = await db.query(
      'SELECT * FROM students_master WHERE LOWER(pin) = LOWER($1)',
      [cleanPin]
    );

    if (masterRes.rows.length === 0) {
      return res.status(404).json({ success: false, error: 'Student master record not found.' });
    }
    const st = masterRes.rows[0];

    // Security check: if student role, they can only view their own certificate/nodues
    if (req.user && req.user.role === 'student' && req.user.pin.toLowerCase() !== cleanPin.toLowerCase()) {
      return res.status(403).json({ success: false, error: 'Access denied: You can only view your own No Dues form.' });
    }

    // Determine branch code and full department title
    const course = st.course_branch || '';
    let branchCode = 'CME';
    let deptName = 'COMPUTER ENGINEERING';

    if (course.toUpperCase().includes('CIVIL')) {
      branchCode = 'CIVIL';
      deptName = 'CIVIL ENGINEERING';
    } else if (course.toUpperCase().includes('MECH')) {
      branchCode = 'MECH';
      deptName = 'MECHANICAL ENGINEERING';
    } else if (course.toUpperCase().includes('ELECTRICAL AND ELECTRONICS') || course.toUpperCase().includes('EEE')) {
      branchCode = 'EEE';
      deptName = 'ELECTRICAL AND ELECTRONICS ENGINEERING';
    } else if (course.toUpperCase().includes('ELECTRONICS AND COMM') || course.toUpperCase().includes('ECE')) {
      branchCode = 'ECE';
      deptName = 'ELECTRONICS AND COMMUNICATION ENGINEERING';
    } else if (course.toUpperCase().includes('BIOMEDICAL') || course.toUpperCase().includes('BME')) {
      branchCode = 'BME';
      deptName = 'BIOMEDICAL ENGINEERING';
    } else if (course.toUpperCase().includes('CHEMICAL') || course.toUpperCase().includes('CHE')) {
      branchCode = 'CHE';
      deptName = 'CHEMICAL ENGINEERING';
    } else if (course.toUpperCase().includes('PHARM')) {
      branchCode = 'PHARM';
      deptName = 'PHARMACY';
    } else {
      branchCode = 'CME';
      deptName = 'COMPUTER ENGINEERING';
    }

    // Determine study period e.g. 2023 - 2026
    let startYear = '2023';
    let endYear = '2026';
    if (st.date_of_admission) {
      const match = st.date_of_admission.match(/\d{4}/);
      if (match) {
        startYear = match[0];
        endYear = String(parseInt(startYear, 10) + 3);
      }
    } else if (cleanPin) {
      const match = cleanPin.match(/^(\d{2})/);
      if (match) {
        startYear = '20' + match[1];
        endYear = String(parseInt(startYear, 10) + 3);
      }
    }
    const studyPeriod = `${startYear} - ${endYear}`;

    // Fetch active request and department clearances for student
    const reqRes = await db.query(
      'SELECT * FROM no_dues_requests WHERE LOWER(student_pin) = LOWER($1) ORDER BY id DESC LIMIT 1',
      [cleanPin]
    );

    let clearances = [];
    if (reqRes.rows.length > 0) {
      const requestId = reqRes.rows[0].id;
      const clearRes = await db.query(
        `SELECT dc.*, d.name as canonical_dept_name
         FROM department_clearances dc
         LEFT JOIN departments d ON d.id = dc.department_id
         WHERE dc.request_id = $1
         ORDER BY dc.id ASC`,
        [requestId]
      );

      clearances = clearRes.rows.map(c => ({
        id: c.department_id,
        name: c.department_name || c.canonical_dept_name,
        status: c.status,
        is_cleared: c.status === 'Approved' || c.status === 'Cleared',
        approved_by: c.approved_by,
        approved_at: c.approved_at
      }));
    }

    // Fallback: if no request submitted yet, fetch applicable departments from DB
    if (clearances.length === 0) {
      const deptsRes = await db.query(
        'SELECT * FROM departments WHERE is_active = 1 AND (branch_code = $1 OR branch_code = $2) ORDER BY id ASC',
        [branchCode, 'ALL']
      );
      clearances = deptsRes.rows.map(d => ({
        id: d.id,
        name: d.name,
        status: 'Pending',
        is_cleared: false
      }));
    }

    return res.json({
      success: true,
      data: {
        student_name: st.student_name,
        student_pin: st.pin,
        father_name: st.father_name,
        course_branch: st.course_branch,
        branch_code: branchCode,
        department_title: `DEPARTMENT OF ${deptName}`,
        admission_no: st.admission_no,
        date_of_admission: st.date_of_admission,
        study_period: studyPeriod,
        clearances
      }
    });
  } catch (err) {
    console.error('getNoDuesFormData error:', err);
    return res.status(500).json({ success: false, error: 'Failed to fetch No Dues form data.' });
  }
}

module.exports = {
  getCertificateDetails,
  getCertificateByVersion,
  getNoDuesFormData
};
