const db = require('../config/db');

async function getCertificateDetails(req, res) {
  try {
    const { student_pin } = req.params;
    const cleanPin = student_pin.trim();

    // Security check: if student role, they can only view their own certificate
    if (req.user && req.user.role === 'student' && req.user.pin !== cleanPin) {
      return res.status(403).json({ success: false, error: 'Access denied: You can only view your own certificate.' });
    }

    // Fetch current active certificate version
    const versionRes = await db.query(
      'SELECT * FROM certificate_versions WHERE student_pin = $1 AND is_current = 1',
      [cleanPin]
    );

    if (versionRes.rows.length === 0) {
      return res.status(404).json({
        success: false,
        error: 'No generated certificate found for this student. Clearance may be pending or certificate has not been generated by the Clerk.'
      });
    }

    const cert = versionRes.rows[0];

    return res.json({
      success: true,
      certificate: cert
    });
  } catch (err) {
    console.error('getCertificateDetails error:', err);
    return res.status(500).json({ success: false, error: 'Failed to fetch certificate details.' });
  }
}

async function getCertificateByVersion(req, res) {
  try {
    const { student_pin, version } = req.params;
    const cleanPin = student_pin.trim();
    const versionNum = parseInt(version, 10);

    // Only Clerk can view specific/superseded versions
    if (!req.user || req.user.role !== 'clerk') {
      return res.status(403).json({
        success: false,
        error: 'Superseded certificate versions are internal records accessible only by the Clerk.'
      });
    }

    const versionRes = await db.query(
      'SELECT * FROM certificate_versions WHERE student_pin = $1 AND version_number = $2',
      [cleanPin, versionNum]
    );

    if (versionRes.rows.length === 0) {
      return res.status(404).json({ success: false, error: `Certificate version v${versionNum} not found.` });
    }

    return res.json({
      success: true,
      certificate: versionRes.rows[0]
    });
  } catch (err) {
    console.error('getCertificateByVersion error:', err);
    return res.status(500).json({ success: false, error: 'Failed to fetch certificate version.' });
  }
}

module.exports = {
  getCertificateDetails,
  getCertificateByVersion
};
